apiVersion: v1
kind: PersistentVolume
metadata:
  name: sparkminio
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: "{{NFS_SERVER_IP}}"
    path: "/data/minio"