apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sparkminio-pvc
  namespace: minio
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: sparkminio