apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-volume0
  labels:
    size-category: 100Gi
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/fedora/k8pv1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - multivac-k8s-rhb7pthanbta-minion-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-volume1
  labels:
    size-category: 100Gi
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/fedora/k8pv1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - multivac-k8s-rhb7pthanbta-minion-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-volume2
  labels:
    size-category: 100Gi
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/fedora/k8pv1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - multivac-k8s-rhb7pthanbta-minion-2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-volume3
  labels:
    size-category: 100Gi
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/fedora/k8pv1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - multivac-k8s-rhb7pthanbta-minion-3
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-volume4
  labels:
    size-category: 100Gi
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/fedora/k8pv1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - multivac-k8s-rhb7pthanbta-minion-4
